{% set name = "distopia" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/MDAnalysis/{{ name }}.git
  git_rev: "5359e51"
  git_depth: -1


build:
  script: "{{ PYTHON }} setup.py install"
  number: 0
  script_env:
   - SKBUILD_CONFIGURE_OPTIONS=-DDISTOPIA_BUILD_TESTS=OFF -DDISTOPIA_USE_EXTERNAL_HWY=ON
  detect_binary_files_with_prefix: False
  ignore_prefix_files: True

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pip
    - python >=3.6
    - versioningit
    - cython
  host:
    - python >=3.6
    - pip
    - numpy <2.0a0
    - scikit-build >=0.17 # for SKBUILD_CONFIGURE_OPTIONS
    - cython
    - versioningit
    - make
    - ninja
    - libhwy
  run:
    - python >=3.6
    - numpy {{ numpy }}
    - libhwy

test:
  imports:
    - distopia
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MDAnalysis/distopia
  summary: Fast distance calculations using explicitly vectorised SIMD
  description: |
    Distopia is a package to rapidly calculate distances under periodic boundary conditions. 
    Explicit SIMD vectorisation allows awesome speedups over autovectorised code.
    The distopia package consists of consists of the python layer (distopia)
    and a C++ library (libdistopia) that does the heavy lifting.

  license: MIT
  license_file:
    - LICENSE.txt


  doc_url: https://www.mdanalysis.org/distopia/
  dev_url: https://github.com/MDAnalysis/distopia

extra:
  recipe-maintainers:
    - IAlibay
    - hmacdope
    - richardjgowers
    - orbeckst
