{% set name = "distopia" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/distopia-{{ version }}.tar.gz
  sha256: a304d0000a397a2cb97f8c82d02655478eec8df20a858e82c2021bfaaf441d7f

build:
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
  host:
    - python
    - pip
    - numpy
    - scikit-build
    - cython
    - versioneer >=0.26
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - distopia
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MDAnalysis/distopia
  summary: Fast distance calculations using explicitly vectorised SIMD
  description: |
    Distopia is a package to rapidly calculate distances under periodic boundary conditions. 
    Explicit SIMD vectorisation allows awesome speedups over autovectorised code.
    The distopia package consists of consists of the python layer (distopia)
    and a C++ library (libdistopia) that does the heavy lifting.

  license: MIT
  license_file:
    - LICENSE.txt


  doc_url: https://www.mdanalysis.org/distopia/
  dev_url: https://github.com/MDAnalysis/distopia

extra:
  recipe-maintainers:
    - hmacdope
    - richardjgowers
    - orbeckst
